Improve coverage
c10k/net pull request #19
Opened 2017-03-23 12:28 UTC by tkhurana96

2017-03-23 15:16 UTC, agauniyal requested changes

2017-03-23 15:16 UTC, agauniyal commented on examples/socket_unix_udp_client.cpp
> +			return methods::construct(s, &clientPath.front());
why not `.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on examples/socket_unix_udp_client.cpp
> +		unixClient.connect(&serverPath.front());
`.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on examples/socket_unix_udp_server.cpp
> +			return methods::construct(s, &serverPath.front());
`.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_connect_test.cpp
> +	std::this_thread::sleep_for(2s);
try lowering `2s` delay if possible.

2017-03-23 15:16 UTC, agauniyal commented on test/socket_constructor_test.cpp
> +	EXPECT_NO_THROW(Socket otherS(Socket(Domain::IPv4, Type::TCP)));
What is this?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_send_test.cpp
> +	myServerSocket.start("::1", 16000);  // just binding
yes this will just bind because `listen` only works for `Connections`.

2017-03-23 15:16 UTC, agauniyal commented on test/socket_send_test.cpp
> +	myServerSocket.start("127.0.0.1", 15000);  // just binding
yes this will just bind because `listen` only works for `Connections`.

2017-03-23 15:16 UTC, agauniyal commented on test/socket_connect_test.cpp
> +	                          &unixPathServer.front());
`.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_connect_test.cpp
> +		return methods::construct(s, &unixPathClient.front());
`.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_connect_test.cpp
> +	clientUnixTCP.close();
shouldn't need to explicitly call `close()` here, ending `}` is on next line only.

2017-03-23 15:16 UTC, agauniyal commented on test/socket_connect_test.cpp
> +	  [&]() { runUnixServer(serverUnixUDP, &unixPathServer.front()); });
`.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_connect_test.cpp
> +		return methods::construct(s, &unixPathServer.front());
`.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_connect_test.cpp
> +		return methods::construct(s, &unixPathClient.front());
`.c_str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_read_write_test.cpp
> +	EXPECT_EQ(res, readTest::msg);
Why using `EXPECT_EQ`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_read_write_test.cpp
> +	EXPECT_EQ(msg, res);
Why using `EXPECT_EQ`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_read_write_test.cpp
> +	EXPECT_EQ(res, readTest::msg);
Why using `EXPECT_EQ`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_read_write_test.cpp
> +		return methods::construct(s, &readTest::unixClientPath1.front());
`.c.str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_read_write_test.cpp
> +	EXPECT_NO_THROW(unixClient1.connect(&readTest::unixServerPath1.front()));
`.c.str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_read_write_test.cpp
> +		return methods::construct(s, &readTest::unixClientPath2.front());
`.c.str()`?

2017-03-23 15:16 UTC, agauniyal commented on test/socket_read_write_test.cpp
> +	EXPECT_NO_THROW(unixClient2.connect(&readTest::unixServerPath2.front()));
`.c.str()`?

2017-03-23 17:09 UTC, tkhurana96 commented on test/socket_constructor_test.cpp
> +	EXPECT_NO_THROW(Socket otherS(Socket(Domain::IPv4, Type::TCP)));
trying the constructor which takes an rvalue

2017-03-23 17:34 UTC, agauniyal commented on test/socket_constructor_test.cpp
> +	EXPECT_NO_THROW(Socket otherS(Socket(Domain::IPv4, Type::TCP)));
@tkhurana96 try with a `vector.emplace()` kind of method then, which is more practical example.

2017-03-24 18:46 UTC, agauniyal approved these changes

2017-03-24 18:46 UTC, merged