Try to add documentation in socket.hpp
c10k/net pull request #4
Opened 2017-02-23 15:19 UTC by tkhurana96

But at "!!Improve This!!" sentences need to be completed.

2017-02-23 16:10 UTC, agauniyal requested changes

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
> +	* @param {_______} args Flags, destination sockaddr objects and their lengths. 		!!Improve This!!
_____ = parameter_pack

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
> +	* @param {_______} args Flags, destination sockaddr objects and their lengths. 		!!Improve This!!
_____ = parameter_pack

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
>  namespace net {
Please format with `clang-format`.

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
> +	* Connects net::Socket to _______ if successful else throws runtime_error exception.		!!Improve This!!
_______ = ipv4 peer

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
> +	* Connects net::Socket to _______ if successful else throws runtime_error exception.		!!Improve This!!
_______ = ipv6 peer

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
> +	* Connects net::Socket to _______ if successful else throws runtime_error exception.		!!Improve This!!
_______ = unix socket peer

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
>  	void stop(SF::shut s) const noexcept
Please make it `_s` instead of `s` both in documentation and function definition.

2017-02-23 16:10 UTC, agauniyal commented on include/socket.hpp
> +	* @param {net::SF::sockOpt} _opValue ___________			!!Improve This!!.
___________ = socket option structure. Present inside socket_family.hpp

2017-02-23 16:54 UTC, tkhurana96 commented
The commit msg was actually: 	Add clang formatted doc and remove all !!Improve This!! from doc

2017-02-23 18:17 UTC, agauniyal commented
@tkhurana96 Since no one else is working on your branch, execute this - 
`git commit --amend -m "Add clang formatted doc and remove all !!Improve This!! comments"` 

and then execute -
`git push -f`.

2017-02-24 06:51 UTC, agauniyal commented
@tkhurana96 there is `net::methods` inside `socket_family.hpp`, would you mind adding theirs too.

2017-02-24 18:54 UTC, agauniyal approved these changes

2017-02-24 18:55 UTC, merged